### ISSUE TITLE
Form phamarcien

### ISSUE THREAD

**Issue by iLdro** [iLdro/MasterCampOrdo#5]
Si quelqu'un peux me donner les variables du form pharmarcien @ValentinLabrune @DorianLB1 @Edran0111

**Comment by Edran0111** [comment]
- nom/prénom/email(responsable pharmacie), 
- nom pharmacie 
- lieu d'exercice
- téléphone pharmacie
- code RPPS responsable pharmacie

**Comment by iLdro** [comment]
Les champs d'adresses il faut les diviser en 

Numero 
Rue
Code Postal
Ville
